Run container as non-root user
adobe-apiplatform/apigateway pull request #41
Opened 2016-10-27 17:25 UTC by srjayep

Create a non-root user for the container in the Dockerfile for the container image.
Made changes to Dockerfile to include the non-root user "apiplatform" 
Made changes to init.sh to sudo run chown using non-root user "apiplatform"
Result of the changes (example run). 
docker ps --quiet | xargs docker inspect --format '{{ .Id }}: User={{.Config.User}}'
919da15af3df3f12d966659a37898b2dd4cbb7837f2989749adf14f6d430284c: **User=apiplatform**

2016-10-27 22:51 UTC, ddragosd requested changes

2016-10-27 22:51 UTC, ddragosd commented on Dockerfile
> +    NAXSI_VERSION=0.53-2 \
NAXSI has been recentele taken out due to license incompatibility.See latest commit.

2016-10-27 22:51 UTC, ddragosd commented on Dockerfile
> +ENV REQUEST_VALIDATION_VERSION 1.1.1
Pls fix the incorrect module version.

2016-10-27 22:51 UTC, ddragosd commented on Dockerfile
> +ENV ZMQ_ADAPTOR_VERSION 0.1.1
Please fix the module version to the latest release.

2016-11-02 06:40 UTC, ddragosd commented on api-gateway-config/conf.d/default.conf
> +    listen 8080 default_server;
do we need to switch to port `8080` instead of `80` ?

2016-11-09 21:12 UTC, ddragosd approved these changes

2016-11-14 22:43 UTC, ddragosd commented
@jkt628 I wanted to get your feedback on this PR before merging it as it may impact a little your WIP.

2016-11-15 00:02 UTC, jkt628 commented
thanks, @ddragosd , i do need to investigate this with @MikeWillCook.

2016-11-17 15:44 UTC, adrocknaphobia commented
@jkt628 @MikeWillCook We're going to need to merge this today. Have you had a had a chance to review?

2016-11-17 17:59 UTC, jkt628 commented
no, moving into holidays which is very busy for Analytics, just merge it and i'll deal with the fall out later.

2016-12-06 01:03 UTC, merged